name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sync with upstream
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Add upstream
        git remote add upstream https://github.com/j-hc/revanced-magisk-module.git || true
        git fetch upstream
        git checkout main

        # Merge upstream into your fork
        git merge upstream/main --no-edit || true

        # Push changes back to your fork
        git push origin main
